const countryOptionsEN = [
  { id: 1, value: "AF", label: "Afghanistan" },
  { id: 2, value: "AX", label: "Aland Islands" },
  { id: 3, value: "AL", label: "Albania" },
  { id: 4, value: "DZ", label: "Algeria" },
  { id: 5, value: "AS", label: "American Samoa" },
  { id: 6, value: "AD", label: "Andorra" },
  { id: 7, value: "AO", label: "Angola" },
  { id: 8, value: "AI", label: "Anguilla" },
  { id: 9, value: "AQ", label: "Antarctica" },
  { id: 10, value: "AG", label: "Antigua and Barbuda" },
  { id: 11, value: "AR", label: "Argentina" },
  { id: 12, value: "AM", label: "Armenia" },
  { id: 13, value: "AW", label: "Aruba" },
  { id: 14, value: "AU", label: "Australia" },
  { id: 15, value: "AT", label: "Austria" },
  { id: 16, value: "AZ", label: "Azerbaijan" },
  { id: 17, value: "BS", label: "Bahamas" },
  { id: 18, value: "BH", label: "Bahrain" },
  { id: 19, value: "BD", label: "Bangladesh" },
  { id: 20, value: "BB", label: "Barbados" },
  { id: 21, value: "BY", label: "Belarus" },
  { id: 22, value: "BE", label: "Belgium" },
  { id: 23, value: "BZ", label: "Belize" },
  { id: 24, value: "BJ", label: "Benin" },
  { id: 25, value: "BM", label: "Bermuda" },
  { id: 26, value: "BT", label: "Bhutan" },
  { id: 27, value: "BO", label: "Bolivia" },
  { id: 28, value: "BQ", label: "Bonaire, Sint Eustatius and Saba" },
  { id: 29, value: "BA", label: "Bosnia and Herzegovina" },
  { id: 30, value: "BW", label: "Botswana" },
  { id: 31, value: "BV", label: "Bouvet Island" },
  { id: 32, value: "BR", label: "Brazil" },
  { id: 33, value: "IO", label: "British Indian Ocean Territory" },
  { id: 34, value: "BN", label: "Brunei Darussalam" },
  { id: 35, value: "BG", label: "Bulgaria" },
  { id: 36, value: "BF", label: "Burkina Faso" },
  { id: 37, value: "BI", label: "Burundi" },
  { id: 38, value: "KH", label: "Cambodia" },
  { id: 39, value: "CM", label: "Cameroon" },
  { id: 40, value: "CA", label: "Canada" },
  { id: 41, value: "CV", label: "Cape Verde" },
  { id: 42, value: "KY", label: "Cayman Islands" },
  { id: 43, value: "CF", label: "Central African Republic" },
  { id: 44, value: "TD", label: "Chad" },
  { id: 45, value: "CL", label: "Chile" },
  { id: 46, value: "CN", label: "China" },
  { id: 47, value: "CX", label: "Christmas Island" },
  { id: 48, value: "CC", label: "Cocos (Keeling) Islands" },
  { id: 49, value: "CO", label: "Colombia" },
  { id: 50, value: "KM", label: "Comoros" },
  { id: 51, value: "CG", label: "Congo" },
  { id: 52, value: "CD", label: "Congo, Democratic Republic of the Congo" },
  { id: 53, value: "CK", label: "Cook Islands" },
  { id: 54, value: "CR", label: "Costa Rica" },
  { id: 55, value: "CI", label: "Cote D'Ivoire" },
  { id: 56, value: "HR", label: "Croatia" },
  { id: 57, value: "CU", label: "Cuba" },
  { id: 58, value: "CW", label: "Curacao" },
  { id: 59, value: "CY", label: "Cyprus" },
  { id: 60, value: "CZ", label: "Czech Republic" },
  { id: 61, value: "DK", label: "Denmark" },
  { id: 62, value: "DJ", label: "Djibouti" },
  { id: 63, value: "DM", label: "Dominica" },
  { id: 64, value: "DO", label: "Dominican Republic" },
  { id: 65, value: "EC", label: "Ecuador" },
  { id: 66, value: "EG", label: "Egypt" },
  { id: 67, value: "SV", label: "El Salvador" },
  { id: 68, value: "GQ", label: "Equatorial Guinea" },
  { id: 69, value: "ER", label: "Eritrea" },
  { id: 70, value: "EE", label: "Estonia" },
  { id: 71, value: "ET", label: "Ethiopia" },
  { id: 72, value: "FK", label: "Falkland Islands (Malvinas)" },
  { id: 73, value: "FO", label: "Faroe Islands" },
  { id: 74, value: "FJ", label: "Fiji" },
  { id: 75, value: "FI", label: "Finland" },
  { id: 76, value: "FR", label: "France" },
  { id: 77, value: "GF", label: "French Guiana" },
  { id: 78, value: "PF", label: "French Polynesia" },
  { id: 79, value: "TF", label: "French Southern Territories" },
  { id: 80, value: "GA", label: "Gabon" },
  { id: 81, value: "GM", label: "Gambia" },
  { id: 82, value: "GE", label: "Georgia" },
  { id: 83, value: "DE", label: "Germany" },
  { id: 84, value: "GH", label: "Ghana" },
  { id: 85, value: "GI", label: "Gibraltar" },
  { id: 86, value: "GR", label: "Greece" },
  { id: 87, value: "GL", label: "Greenland" },
  { id: 88, value: "GD", label: "Grenada" },
  { id: 89, value: "GP", label: "Guadeloupe" },
  { id: 90, value: "GU", label: "Guam" },
  { id: 91, value: "GT", label: "Guatemala" },
  { id: 92, value: "GG", label: "Guernsey" },
  { id: 93, value: "GN", label: "Guinea" },
  { id: 94, value: "GW", label: "Guinea-Bissau" },
  { id: 95, value: "GY", label: "Guyana" },
  { id: 96, value: "HT", label: "Haiti" },
  { id: 97, value: "HM", label: "Heard Island and Mcdonald Islands" },
  { id: 98, value: "VA", label: "Holy See (Vatican City State)" },
  { id: 99, value: "HN", label: "Honduras" },
  { id: 100, value: "HK", label: "Hong Kong" },
  { id: 101, value: "HU", label: "Hungary" },
  { id: 102, value: "IS", label: "Iceland" },
  { id: 103, value: "IN", label: "India" },
  { id: 104, value: "ID", label: "Indonesia" },
  { id: 105, value: "IR", label: "Iran, Islamic Republic of" },
  { id: 106, value: "IQ", label: "Iraq" },
  { id: 107, value: "IE", label: "Ireland" },
  { id: 108, value: "IM", label: "Isle of Man" },
  { id: 109, value: "IL", label: "Israel" },
  { id: 110, value: "IT", label: "Italy" },
  { id: 111, value: "JM", label: "Jamaica" },
  { id: 112, value: "JP", label: "Japan" },
  { id: 113, value: "JE", label: "Jersey" },
  { id: 114, value: "JO", label: "Jordan" },
  { id: 115, value: "KZ", label: "Kazakhstan" },
  { id: 116, value: "KE", label: "Kenya" },
  { id: 117, value: "KI", label: "Kiribati" },
  { id: 118, value: "KP", label: "Korea, Democratic People's Republic of" },
  { id: 119, value: "KR", label: "Korea, Republic of" },
  { id: 120, value: "XK", label: "Kosovo" },
  { id: 121, value: "KW", label: "Kuwait" },
  { id: 122, value: "KG", label: "Kyrgyzstan" },
  { id: 123, value: "LA", label: "Lao People's Democratic Republic" },
  { id: 124, value: "LV", label: "Latvia" },
  { id: 125, value: "LB", label: "Lebanon" },
  { id: 126, value: "LS", label: "Lesotho" },
  { id: 127, value: "LR", label: "Liberia" },
  { id: 128, value: "LY", label: "Libyan Arab Jamahiriya" },
  { id: 129, value: "LI", label: "Liechtenstein" },
  { id: 130, value: "LT", label: "Lithuania" },
  { id: 131, value: "LU", label: "Luxembourg" },
  { id: 132, value: "MO", label: "Macao" },
  { id: 133, value: "MK", label: "Macedonia, the Former Yugoslav Republic of" },
  { id: 134, value: "MG", label: "Madagascar" },
  { id: 135, value: "MW", label: "Malawi" },
  { id: 136, value: "MY", label: "Malaysia" },
  { id: 137, value: "MV", label: "Maldives" },
  { id: 138, value: "ML", label: "Mali" },
  { id: 139, value: "MT", label: "Malta" },
  { id: 140, value: "MH", label: "Marshall Islands" },
  { id: 141, value: "MQ", label: "Martinique" },
  { id: 142, value: "MR", label: "Mauritania" },
  { id: 143, value: "MU", label: "Mauritius" },
  { id: 144, value: "YT", label: "Mayotte" },
  { id: 145, value: "MX", label: "Mexico" },
  { id: 146, value: "FM", label: "Micronesia, Federated States of" },
  { id: 147, value: "MD", label: "Moldova, Republic of" },
  { id: 148, value: "MC", label: "Monaco" },
  { id: 149, value: "MN", label: "Mongolia" },
  { id: 150, value: "ME", label: "Montenegro" },
  { id: 151, value: "MS", label: "Montserrat" },
  { id: 152, value: "MA", label: "Morocco" },
  { id: 153, value: "MZ", label: "Mozambique" },
  { id: 154, value: "MM", label: "Myanmar" },
  { id: 155, value: "NA", label: "Namibia" },
  { id: 156, value: "NR", label: "Nauru" },
  { id: 157, value: "NP", label: "Nepal" },
  { id: 158, value: "NL", label: "Netherlands" },
  { id: 159, value: "AN", label: "Netherlands Antilles" },
  { id: 160, value: "NC", label: "New Caledonia" },
  { id: 161, value: "NZ", label: "New Zealand" },
  { id: 162, value: "NI", label: "Nicaragua" },
  { id: 163, value: "NE", label: "Niger" },
  { id: 164, value: "NG", label: "Nigeria" },
  { id: 165, value: "NU", label: "Niue" },
  { id: 166, value: "NF", label: "Norfolk Island" },
  { id: 167, value: "MP", label: "Northern Mariana Islands" },
  { id: 168, value: "NO", label: "Norway" },
  { id: 169, value: "OM", label: "Oman" },
  { id: 170, value: "PK", label: "Pakistan" },
  { id: 171, value: "PW", label: "Palau" },
  { id: 172, value: "PS", label: "Palestinian Territory, Occupied" },
  { id: 173, value: "PA", label: "Panama" },
  { id: 174, value: "PG", label: "Papua New Guinea" },
  { id: 175, value: "PY", label: "Paraguay" },
  { id: 176, value: "PE", label: "Peru" },
  { id: 177, value: "PH", label: "Philippines" },
  { id: 178, value: "PN", label: "Pitcairn" },
  { id: 179, value: "PL", label: "Poland" },
  { id: 180, value: "PT", label: "Portugal" },
  { id: 181, value: "PR", label: "Puerto Rico" },
  { id: 182, value: "QA", label: "Qatar" },
  { id: 183, value: "RE", label: "Reunion" },
  { id: 184, value: "RO", label: "Romania" },
  { id: 185, value: "RU", label: "Russian Federation" },
  { id: 186, value: "RW", label: "Rwanda" },
  { id: 187, value: "BL", label: "Saint Barthelemy" },
  { id: 188, value: "SH", label: "Saint Helena" },
  { id: 189, value: "KN", label: "Saint Kitts and Nevis" },
  { id: 190, value: "LC", label: "Saint Lucia" },
  { id: 191, value: "MF", label: "Saint Martin" },
  { id: 192, value: "PM", label: "Saint Pierre and Miquelon" },
  { id: 193, value: "VC", label: "Saint Vincent and the Grenadines" },
  { id: 194, value: "WS", label: "Samoa" },
  { id: 195, value: "SM", label: "San Marino" },
  { id: 196, value: "ST", label: "Sao Tome and Principe" },
  { id: 197, value: "SA", label: "Saudi Arabia" },
  { id: 198, value: "SN", label: "Senegal" },
  { id: 199, value: "RS", label: "Serbia" },
  { id: 200, value: "CS", label: "Serbia and Montenegro" },
  { id: 201, value: "SC", label: "Seychelles" },
  { id: 202, value: "SL", label: "Sierra Leone" },
  { id: 203, value: "SG", label: "Singapore" },
  { id: 204, value: "SX", label: "Sint Maarten" },
  { id: 205, value: "SK", label: "Slovakia" },
  { id: 206, value: "SI", label: "Slovenia" },
  { id: 207, value: "SB", label: "Solomon Islands" },
  { id: 208, value: "SO", label: "Somalia" },
  { id: 209, value: "ZA", label: "South Africa" },
  {
    id: 210,
    value: "GS",
    label: "South Georgia and the South Sandwich Islands",
  },
  { id: 211, value: "SS", label: "South Sudan" },
  { id: 212, value: "ES", label: "Spain" },
  { id: 213, value: "LK", label: "Sri Lanka" },
  { id: 214, value: "SD", label: "Sudan" },
  { id: 215, value: "SR", label: "Suriname" },
  { id: 216, value: "SJ", label: "Svalbard and Jan Mayen" },
  { id: 217, value: "SZ", label: "Swaziland" },
  { id: 218, value: "SE", label: "Sweden" },
  { id: 219, value: "CH", label: "Switzerland" },
  { id: 220, value: "SY", label: "Syrian Arab Republic" },
  { id: 221, value: "TW", label: "Taiwan, Province of China" },
  { id: 222, value: "TJ", label: "Tajikistan" },
  { id: 223, value: "TZ", label: "Tanzania, United Republic of" },
  { id: 224, value: "TH", label: "Thailand" },
  { id: 225, value: "TL", label: "Timor-Leste" },
  { id: 226, value: "TG", label: "Togo" },
  { id: 227, value: "TK", label: "Tokelau" },
  { id: 228, value: "TO", label: "Tonga" },
  { id: 229, value: "TT", label: "Trinidad and Tobago" },
  { id: 230, value: "TN", label: "Tunisia" },
  { id: 231, value: "TR", label: "Turkey" },
  { id: 232, value: "TM", label: "Turkmenistan" },
  { id: 233, value: "TC", label: "Turks and Caicos Islands" },
  { id: 234, value: "TV", label: "Tuvalu" },
  { id: 235, value: "UG", label: "Uganda" },
  { id: 236, value: "UA", label: "Ukraine" },
  { id: 237, value: "AE", label: "United Arab Emirates" },
  { id: 238, value: "GB", label: "United Kingdom" },
  { id: 239, value: "US", label: "United States" },
  { id: 240, value: "UM", label: "United States Minor Outlying Islands" },
  { id: 241, value: "UY", label: "Uruguay" },
  { id: 242, value: "UZ", label: "Uzbekistan" },
  { id: 243, value: "VU", label: "Vanuatu" },
  { id: 244, value: "VE", label: "Venezuela" },
  { id: 245, value: "VN", label: "Viet Nam" },
  { id: 246, value: "VG", label: "Virgin Islands, British" },
  { id: 247, value: "VI", label: "Virgin Islands, U.s." },
  { id: 248, value: "WF", label: "Wallis and Futuna" },
  { id: 249, value: "EH", label: "Western Sahara" },
  { id: 250, value: "YE", label: "Yemen" },
  { id: 251, value: "ZM", label: "Zambia" },
  { id: 252, value: "ZW", label: "Zimbabwe" },
];
const countryOptionsFR = [
  { id: 1, value: "AF", label: "L'Afghanistan" },
  { id: 2, value: "AX", label: "Iles Aland" },
  { id: 3, value: "AL", label: "Albanie" },
  { id: 4, value: "DZ", label: "Algérie" },
  { id: 5, value: "AS", label: "Samoa américaines" },
  { id: 6, value: "AD", label: "Andorre" },
  { id: 7, value: "AO", label: "L'Angola" },
  { id: 8, value: "AI", label: "Anguilla" },
  { id: 9, value: "AQ", label: "Antarctique" },
  { id: 10, value: "AG", label: "Antigua-et-Barbuda" },
  { id: 11, value: "AR", label: "Argentine" },
  { id: 12, value: "AM", label: "Arménie" },
  { id: 13, value: "AW", label: "Aruba" },
  { id: 14, value: "AU", label: "Australie" },
  { id: 15, value: "AT", label: "L'Autriche" },
  { id: 16, value: "AZ", label: "Azerbaïdjan" },
  { id: 17, value: "BS", label: "Bahamas" },
  { id: 18, value: "BH", label: "Bahreïn" },
  { id: 19, value: "BD", label: "Bangladesh" },
  { id: 20, value: "BB", label: "Barbade" },
  { id: 21, value: "BY", label: "Biélorussie" },
  { id: 22, value: "BE", label: "Belgique" },
  { id: 23, value: "BZ", label: "Belize" },
  { id: 24, value: "BJ", label: "Bénin" },
  { id: 25, value: "BM", label: "Bermudes" },
  { id: 26, value: "BT", label: "Bhoutan" },
  { id: 27, value: "BO", label: "Bolivie" },
  { id: 28, value: "BQ", label: "Bonaire, Saint-Eustache et Saba" },
  { id: 29, value: "BA", label: "Bosnie Herzégovine" },
  { id: 30, value: "BW", label: "Botswana" },
  { id: 31, value: "BV", label: "Île Bouvet" },
  { id: 32, value: "BR", label: "Brésil" },
  { id: 33, value: "IO", label: "Territoire britannique de l'océan Indien" },
  { id: 34, value: "BN", label: "Brunei Darussalam" },
  { id: 35, value: "BG", label: "Bulgarie" },
  { id: 36, value: "BF", label: "Burkina Faso" },
  { id: 37, value: "BI", label: "Burundi" },
  { id: 38, value: "KH", label: "Cambodge" },
  { id: 39, value: "CM", label: "Cameroun" },
  { id: 40, value: "CA", label: "Canada" },
  { id: 41, value: "CV", label: "Cap-Vert" },
  { id: 42, value: "KY", label: "Îles Caïmans" },
  { id: 43, value: "CF", label: "République centrafricaine" },
  { id: 44, value: "TD", label: "Tchad" },
  { id: 45, value: "CL", label: "Chili" },
  { id: 46, value: "CN", label: "Chine" },
  { id: 47, value: "CX", label: "L'île de noël" },
  { id: 48, value: "CC", label: "Îles Cocos (Keeling)" },
  { id: 49, value: "CO", label: "Colombie" },
  { id: 50, value: "KM", label: "Comores" },
  { id: 51, value: "CG", label: "Congo" },
  { id: 52, value: "CD", label: "Congo, République démocratique du Congo" },
  { id: 53, value: "CK", label: "les Îles Cook" },
  { id: 54, value: "CR", label: "Costa Rica" },
  { id: 55, value: "CI", label: "Côte d'Ivoire" },
  { id: 56, value: "HR", label: "Croatie" },
  { id: 57, value: "CU", label: "Cuba" },
  { id: 58, value: "CW", label: "Curacao" },
  { id: 59, value: "CY", label: "Chypre" },
  { id: 60, value: "CZ", label: "République Tchèque" },
  { id: 61, value: "DK", label: "Danemark" },
  { id: 62, value: "DJ", label: "Djibouti" },
  { id: 63, value: "DM", label: "Dominique" },
  { id: 64, value: "DO", label: "République dominicaine" },
  { id: 65, value: "EC", label: "Equateur" },
  { id: 66, value: "EG", label: "Egypte" },
  { id: 67, value: "SV", label: "Le Salvador" },
  { id: 68, value: "GQ", label: "Guinée Équatoriale" },
  { id: 69, value: "ER", label: "Érythrée" },
  { id: 70, value: "EE", label: "Estonie" },
  { id: 71, value: "ET", label: "Ethiopie" },
  { id: 72, value: "FK", label: "Îles Falkland (Malvinas)" },
  { id: 73, value: "FO", label: "Îles Féroé" },
  { id: 74, value: "FJ", label: "Fidji" },
  { id: 75, value: "FI", label: "Finlande" },
  { id: 76, value: "FR", label: "France" },
  { id: 77, value: "GF", label: "Guyane Française" },
  { id: 78, value: "PF", label: "Polynésie française" },
  { id: 79, value: "TF", label: "Terres australes françaises" },
  { id: 80, value: "GA", label: "Gabon" },
  { id: 81, value: "GM", label: "Gambie" },
  { id: 82, value: "GE", label: "Géorgie" },
  { id: 83, value: "DE", label: "Allemagne" },
  { id: 84, value: "GH", label: "Ghana" },
  { id: 85, value: "GI", label: "Gibraltar" },
  { id: 86, value: "GR", label: "Grèce" },
  { id: 87, value: "GL", label: "Groenland" },
  { id: 88, value: "GD", label: "Grenade" },
  { id: 89, value: "GP", label: "Guadeloupe" },
  { id: 90, value: "GU", label: "Guam" },
  { id: 91, value: "GT", label: "Guatemala" },
  { id: 92, value: "GG", label: "Guernesey" },
  { id: 93, value: "GN", label: "Guinée" },
  { id: 94, value: "GW", label: "Guinée-Bissau" },
  { id: 95, value: "GY", label: "Guyane" },
  { id: 96, value: "HT", label: "Haïti" },
  { id: 97, value: "HM", label: "Îles Heard et McDonald" },
  { id: 98, value: "VA", label: "Saint-Siège (État de la Cité du Vatican)" },
  { id: 99, value: "HN", label: "Honduras" },
  { id: 100, value: "HK", label: "Hong Kong" },
  { id: 101, value: "HU", label: "Hongrie" },
  { id: 102, value: "IS", label: "Islande" },
  { id: 103, value: "IN", label: "Inde" },
  { id: 104, value: "ID", label: "Indonésie" },
  { id: 105, value: "IR", label: "Iran (République islamique d" },
  { id: 106, value: "IQ", label: "Irak" },
  { id: 107, value: "IE", label: "Irlande" },
  { id: 108, value: "IM", label: "île de Man" },
  { id: 109, value: "IL", label: "Israël" },
  { id: 110, value: "IT", label: "Italie" },
  { id: 111, value: "JM", label: "Jamaïque" },
  { id: 112, value: "JP", label: "Japon" },
  { id: 113, value: "JE", label: "Jersey" },
  { id: 114, value: "JO", label: "Jordan" },
  { id: 115, value: "KZ", label: "Kazakhstan" },
  { id: 116, value: "KE", label: "Kenya" },
  { id: 117, value: "KI", label: "Kiribati" },
  { id: 118, value: "KP", label: "République populaire démocratique de Corée" },
  { id: 119, value: "KR", label: "Corée, République de" },
  { id: 120, value: "XK", label: "Kosovo" },
  { id: 121, value: "KW", label: "Koweit" },
  { id: 122, value: "KG", label: "Kirghizistan" },
  { id: 123, value: "LA", label: "République démocratique populaire lao" },
  { id: 124, value: "LV", label: "Lettonie" },
  { id: 125, value: "LB", label: "Liban" },
  { id: 126, value: "LS", label: "Lesotho" },
  { id: 127, value: "LR", label: "Libéria" },
  { id: 128, value: "LY", label: "Jamahiriya arabe libyenne" },
  { id: 129, value: "LI", label: "Liechtenstein" },
  { id: 130, value: "LT", label: "Lituanie" },
  { id: 131, value: "LU", label: "Luxembourg" },
  { id: 132, value: "MO", label: "Macao" },
  {
    id: 133,
    value: "MK",
    label: "Macédoine, ancienne République yougoslave de",
  },
  { id: 134, value: "MG", label: "Madagascar" },
  { id: 135, value: "MW", label: "Malawi" },
  { id: 136, value: "MY", label: "Malaisie" },
  { id: 137, value: "MV", label: "Maldives" },
  { id: 138, value: "ML", label: "Mali" },
  { id: 139, value: "MT", label: "Malte" },
  { id: 140, value: "MH", label: "Iles Marshall" },
  { id: 141, value: "MQ", label: "Martinique" },
  { id: 142, value: "MR", label: "Mauritanie" },
  { id: 143, value: "MU", label: "Ile Maurice" },
  { id: 144, value: "YT", label: "Mayotte" },
  { id: 145, value: "MX", label: "Mexique" },
  { id: 146, value: "FM", label: "Micronésie, États fédérés de" },
  { id: 147, value: "MD", label: "Moldova, République de" },
  { id: 148, value: "MC", label: "Monaco" },
  { id: 149, value: "MN", label: "Mongolie" },
  { id: 150, value: "ME", label: "Monténégro" },
  { id: 151, value: "MS", label: "Montserrat" },
  { id: 152, value: "MA", label: "Maroc" },
  { id: 153, value: "MZ", label: "Mozambique" },
  { id: 154, value: "MM", label: "Myanmar" },
  { id: 155, value: "NA", label: "Namibie" },
  { id: 156, value: "NR", label: "Nauru" },
  { id: 157, value: "NP", label: "Népal" },
  { id: 158, value: "NL", label: "Pays-Bas" },
  { id: 159, value: "AN", label: "Antilles néerlandaises" },
  { id: 160, value: "NC", label: "Nouvelle Calédonie" },
  { id: 161, value: "NZ", label: "Nouvelle-Zélande" },
  { id: 162, value: "NI", label: "Nicaragua" },
  { id: 163, value: "NE", label: "Niger" },
  { id: 164, value: "NG", label: "Nigeria" },
  { id: 165, value: "NU", label: "Niue" },
  { id: 166, value: "NF", label: "l'ile de Norfolk" },
  { id: 167, value: "MP", label: "Îles Mariannes du Nord" },
  { id: 168, value: "NO", label: "Norvège" },
  { id: 169, value: "OM", label: "Oman" },
  { id: 170, value: "PK", label: "Pakistan" },
  { id: 171, value: "PW", label: "Palau" },
  { id: 172, value: "PS", label: "Territoire palestinien, occupé" },
  { id: 173, value: "PA", label: "Panama" },
  { id: 174, value: "PG", label: "Papouasie Nouvelle Guinée" },
  { id: 175, value: "PY", label: "Paraguay" },
  { id: 176, value: "PE", label: "Pérou" },
  { id: 177, value: "PH", label: "Philippines" },
  { id: 178, value: "PN", label: "Pitcairn" },
  { id: 179, value: "PL", label: "Pologne" },
  { id: 180, value: "PT", label: "Le Portugal" },
  { id: 181, value: "PR", label: "Porto Rico" },
  { id: 182, value: "QA", label: "Qatar" },
  { id: 183, value: "RE", label: "Réunion" },
  { id: 184, value: "RO", label: "Roumanie" },
  { id: 185, value: "RU", label: "Fédération Russe" },
  { id: 186, value: "RW", label: "Rwanda" },
  { id: 187, value: "BL", label: "Saint Barthélemy" },
  { id: 188, value: "SH", label: "Sainte-Hélène" },
  { id: 189, value: "KN", label: "Saint-Christophe-et-Niévès" },
  { id: 190, value: "LC", label: "Sainte-Lucie" },
  { id: 191, value: "MF", label: "Saint Martin" },
  { id: 192, value: "PM", label: "Saint-Pierre-et-Miquelon" },
  { id: 193, value: "VC", label: "Saint-Vincent-et-les-Grenadines" },
  { id: 194, value: "WS", label: "Samoa" },
  { id: 195, value: "SM", label: "Saint Marin" },
  { id: 196, value: "ST", label: "Sao Tomé et Principe" },
  { id: 197, value: "SA", label: "Arabie Saoudite" },
  { id: 198, value: "SN", label: "Sénégal" },
  { id: 199, value: "RS", label: "Serbie" },
  { id: 200, value: "CS", label: "Serbie et Monténégro" },
  { id: 201, value: "SC", label: "les Seychelles" },
  { id: 202, value: "SL", label: "Sierra Leone" },
  { id: 203, value: "SG", label: "Singapour" },
  { id: 204, value: "SX", label: "St Martin" },
  { id: 205, value: "SK", label: "Slovaquie" },
  { id: 206, value: "SI", label: "Slovénie" },
  { id: 207, value: "SB", label: "Les îles Salomon" },
  { id: 208, value: "SO", label: "Somalie" },
  { id: 209, value: "ZA", label: "Afrique du Sud" },
  { id: 210, value: "GS", label: "Géorgie du Sud et îles Sandwich du Sud" },
  { id: 211, value: "SS", label: "Soudan du sud" },
  { id: 212, value: "ES", label: "Espagne" },
  { id: 213, value: "LK", label: "Sri Lanka" },
  { id: 214, value: "SD", label: "Soudan" },
  { id: 215, value: "SR", label: "Suriname" },
  { id: 216, value: "SJ", label: "Svalbard et Jan Mayen" },
  { id: 217, value: "SZ", label: "Swaziland" },
  { id: 218, value: "SE", label: "Suède" },
  { id: 219, value: "CH", label: "la Suisse" },
  { id: 220, value: "SY", label: "République arabe syrienne" },
  { id: 221, value: "TW", label: "Taiwan, Province de Chine" },
  { id: 222, value: "TJ", label: "Tadjikistan" },
  { id: 223, value: "TZ", label: "Tanzanie, République-Unie de" },
  { id: 224, value: "TH", label: "Thaïlande" },
  { id: 225, value: "TL", label: "Timor-Leste" },
  { id: 226, value: "TG", label: "Aller" },
  { id: 227, value: "TK", label: "Tokelau" },
  { id: 228, value: "TO", label: "Tonga" },
  { id: 229, value: "TT", label: "Trinité-et-Tobago" },
  { id: 230, value: "TN", label: "Tunisie" },
  { id: 231, value: "TR", label: "dinde" },
  { id: 232, value: "TM", label: "Turkménistan" },
  { id: 233, value: "TC", label: "îles Turques-et-Caïques" },
  { id: 234, value: "TV", label: "Tuvalu" },
  { id: 235, value: "UG", label: "Ouganda" },
  { id: 236, value: "UA", label: "Ukraine" },
  { id: 237, value: "AE", label: "Emirats Arabes Unis" },
  { id: 238, value: "GB", label: "Royaume-Uni" },
  { id: 239, value: "US", label: "États-Unis" },
  { id: 240, value: "UM", label: "Îles mineures éloignées des États-Unis" },
  { id: 241, value: "UY", label: "Uruguay" },
  { id: 242, value: "UZ", label: "Ouzbékistan" },
  { id: 243, value: "VU", label: "Vanuatu" },
  { id: 244, value: "VE", label: "Venezuela" },
  { id: 245, value: "VN", label: "Viet Nam" },
  { id: 246, value: "VG", label: "Îles Vierges britanniques" },
  { id: 247, value: "VI", label: "Îles Vierges américaines, États-Unis" },
  { id: 248, value: "WF", label: "Wallis et Futuna" },
  { id: 249, value: "EH", label: "Sahara occidental" },
  { id: 250, value: "YE", label: "Yémen" },
  { id: 251, value: "ZM", label: "Zambie" },
  { id: 252, value: "ZW", label: "Zimbabwe" },
];

const countryOptionsES = [
  { id: 1, value: "AF", label: "Afganistán" },
  { id: 2, value: "AX", label: "Islas Aland" },
  { id: 3, value: "AL", label: "Albania" },
  { id: 4, value: "DZ", label: "Argelia" },
  { id: 5, value: "AS", label: "Samoa Americana" },
  { id: 6, value: "AD", label: "Andorra" },
  { id: 7, value: "AO", label: "Angola" },
  { id: 8, value: "AI", label: "Anguila" },
  { id: 9, value: "AQ", label: "Antártida" },
  { id: 10, value: "AG", label: "Antigua y Barbuda" },
  { id: 11, value: "AR", label: "Argentina" },
  { id: 12, value: "AM", label: "Armenia" },
  { id: 13, value: "AW", label: "Aruba" },
  { id: 14, value: "AU", label: "Australia" },
  { id: 15, value: "AT", label: "Austria" },
  { id: 16, value: "AZ", label: "Azerbaiyán" },
  { id: 17, value: "BS", label: "Bahamas" },
  { id: 18, value: "BH", label: "Bahréin" },
  { id: 19, value: "BD", label: "Bangladesh" },
  { id: 20, value: "BB", label: "Barbados" },
  { id: 21, value: "BY", label: "Bielorrusia" },
  { id: 22, value: "BE", label: "Bélgica" },
  { id: 23, value: "BZ", label: "Belice" },
  { id: 24, value: "BJ", label: "Benin" },
  { id: 25, value: "BM", label: "islas Bermudas" },
  { id: 26, value: "BT", label: "Bután" },
  { id: 27, value: "BO", label: "Bolivia" },
  { id: 28, value: "BQ", label: "Bonaire, Sint Eustatius y Saba" },
  { id: 29, value: "BA", label: "Bosnia y Herzegovina" },
  { id: 30, value: "BW", label: "Botswana" },
  { id: 31, value: "BV", label: "Isla Bouvet" },
  { id: 32, value: "BR", label: "Brasil" },
  { id: 33, value: "IO", label: "Territorio Británico del Océano Índico" },
  { id: 34, value: "BN", label: "Brunei Darussalam" },
  { id: 35, value: "BG", label: "Bulgaria" },
  { id: 36, value: "BF", label: "Burkina Faso" },
  { id: 37, value: "BI", label: "Burundi" },
  { id: 38, value: "KH", label: "Camboya" },
  { id: 39, value: "CM", label: "Camerún" },
  { id: 40, value: "CA", label: "Canadá" },
  { id: 41, value: "CV", label: "Cabo Verde" },
  { id: 42, value: "KY", label: "Islas Caimán" },
  { id: 43, value: "CF", label: "República Centroafricana" },
  { id: 44, value: "TD", label: "Chad" },
  { id: 45, value: "CL", label: "Chile" },
  { id: 46, value: "CN", label: "porcelana" },
  { id: 47, value: "CX", label: "Isla de Navidad" },
  { id: 48, value: "CC", label: "Islas Cocos (Keeling)" },
  { id: 49, value: "CO", label: "Colombia" },
  { id: 50, value: "KM", label: "Comoras" },
  { id: 51, value: "CG", label: "Congo" },
  { id: 52, value: "CD", label: "Congo, República Democrática del Congo" },
  { id: 53, value: "CK", label: "Islas Cook" },
  { id: 54, value: "CR", label: "Costa Rica" },
  { id: 55, value: "CI", label: "Costa de Marfil" },
  { id: 56, value: "HR", label: "Croacia" },
  { id: 57, value: "CU", label: "Cuba" },
  { id: 58, value: "CW", label: "Curazao" },
  { id: 59, value: "CY", label: "Chipre" },
  { id: 60, value: "CZ", label: "Republica checa" },
  { id: 61, value: "DK", label: "Dinamarca" },
  { id: 62, value: "DJ", label: "Djibouti" },
  { id: 63, value: "DM", label: "Dominica" },
  { id: 64, value: "DO", label: "República Dominicana" },
  { id: 65, value: "EC", label: "Ecuador" },
  { id: 66, value: "EG", label: "Egipto" },
  { id: 67, value: "SV", label: "El Salvador" },
  { id: 68, value: "GQ", label: "Guinea Ecuatorial" },
  { id: 69, value: "ER", label: "Eritrea" },
  { id: 70, value: "EE", label: "Estonia" },
  { id: 71, value: "ET", label: "Etiopía" },
  { id: 72, value: "FK", label: "Islas Falkland (Malvinas)" },
  { id: 73, value: "FO", label: "Islas Faroe" },
  { id: 74, value: "FJ", label: "Fiyi" },
  { id: 75, value: "FI", label: "Finlandia" },
  { id: 76, value: "FR", label: "Francia" },
  { id: 77, value: "GF", label: "Guayana Francesa" },
  { id: 78, value: "PF", label: "Polinesia francés" },
  { id: 79, value: "TF", label: "Territorios Franceses del Sur" },
  { id: 80, value: "GA", label: "Gabón" },
  { id: 81, value: "GM", label: "Gambia" },
  { id: 82, value: "GE", label: "Georgia" },
  { id: 83, value: "DE", label: "Alemania" },
  { id: 84, value: "GH", label: "Ghana" },
  { id: 85, value: "GI", label: "Gibraltar" },
  { id: 86, value: "GR", label: "Grecia" },
  { id: 87, value: "GL", label: "Groenlandia" },
  { id: 88, value: "GD", label: "Granada" },
  { id: 89, value: "GP", label: "Guadalupe" },
  { id: 90, value: "GU", label: "Guam" },
  { id: 91, value: "GT", label: "Guatemala" },
  { id: 92, value: "GG", label: "Guernsey" },
  { id: 93, value: "GN", label: "Guinea" },
  { id: 94, value: "GW", label: "Guinea-Bissau" },
  { id: 95, value: "GY", label: "Guayana" },
  { id: 96, value: "HT", label: "Haití" },
  { id: 97, value: "HM", label: "Islas Heard y McDonald" },
  {
    id: 98,
    value: "VA",
    label: "Santa Sede (Estado de la Ciudad del Vaticano)",
  },
  { id: 99, value: "HN", label: "Honduras" },
  { id: 100, value: "HK", label: "Hong Kong" },
  { id: 101, value: "HU", label: "Hungría" },
  { id: 102, value: "IS", label: "Islandia" },
  { id: 103, value: "IN", label: "India" },
  { id: 104, value: "ID", label: "Indonesia" },
  { id: 105, value: "IR", label: "Irán (República Islámica de" },
  { id: 106, value: "IQ", label: "Irak" },
  { id: 107, value: "IE", label: "Irlanda" },
  { id: 108, value: "IM", label: "Isla del hombre" },
  { id: 109, value: "IL", label: "Israel" },
  { id: 110, value: "IT", label: "Italia" },
  { id: 111, value: "JM", label: "Jamaica" },
  { id: 112, value: "JP", label: "Japón" },
  { id: 113, value: "JE", label: "Jersey" },
  { id: 114, value: "JO", label: "Jordán" },
  { id: 115, value: "KZ", label: "Kazajstán" },
  { id: 116, value: "KE", label: "Kenia" },
  { id: 117, value: "KI", label: "Kiribati" },
  { id: 118, value: "KP", label: "República de Corea, Popular Democrática de" },
  { id: 119, value: "KR", label: "Corea, república de" },
  { id: 120, value: "XK", label: "Kosovo" },
  { id: 121, value: "KW", label: "Kuwait" },
  { id: 122, value: "KG", label: "Kirguistán" },
  { id: 123, value: "LA", label: "República Democrática Popular Lao" },
  { id: 124, value: "LV", label: "Letonia" },
  { id: 125, value: "LB", label: "Líbano" },
  { id: 126, value: "LS", label: "Lesoto" },
  { id: 127, value: "LR", label: "Liberia" },
  { id: 128, value: "LY", label: "Jamahiriya Arabe Libia" },
  { id: 129, value: "LI", label: "Liechtenstein" },
  { id: 130, value: "LT", label: "Lituania" },
  { id: 131, value: "LU", label: "Luxemburgo" },
  { id: 132, value: "MO", label: "Macao" },
  { id: 133, value: "MK", label: "Macedonia, la ex República Yugoslava de" },
  { id: 134, value: "MG", label: "Madagascar" },
  { id: 135, value: "MW", label: "Malawi" },
  { id: 136, value: "MY", label: "Malasia" },
  { id: 137, value: "MV", label: "Maldivas" },
  { id: 138, value: "ML", label: "Mali" },
  { id: 139, value: "MT", label: "Malta" },
  { id: 140, value: "MH", label: "Islas Marshall" },
  { id: 141, value: "MQ", label: "Martinica" },
  { id: 142, value: "MR", label: "Mauritania" },
  { id: 143, value: "MU", label: "Mauricio" },
  { id: 144, value: "YT", label: "Mayotte" },
  { id: 145, value: "MX", label: "México" },
  { id: 146, value: "FM", label: "Micronesia, Estados Federados de" },
  { id: 147, value: "MD", label: "Moldavia, República de" },
  { id: 148, value: "MC", label: "Mónaco" },
  { id: 149, value: "MN", label: "Mongolia" },
  { id: 150, value: "ME", label: "Montenegro" },
  { id: 151, value: "MS", label: "Montserrat" },
  { id: 152, value: "MA", label: "Marruecos" },
  { id: 153, value: "MZ", label: "Mozambique" },
  { id: 154, value: "MM", label: "Myanmar" },
  { id: 155, value: "NA", label: "Namibia" },
  { id: 156, value: "NR", label: "Nauru" },
  { id: 157, value: "NP", label: "Nepal" },
  { id: 158, value: "NL", label: "Países Bajos" },
  { id: 159, value: "AN", label: "Antillas Holandesas" },
  { id: 160, value: "NC", label: "Nueva Caledonia" },
  { id: 161, value: "NZ", label: "Nueva Zelanda" },
  { id: 162, value: "NI", label: "Nicaragua" },
  { id: 163, value: "NE", label: "Níger" },
  { id: 164, value: "NG", label: "Nigeria" },
  { id: 165, value: "NU", label: "Niue" },
  { id: 166, value: "NF", label: "Isla Norfolk" },
  { id: 167, value: "MP", label: "Islas Marianas del Norte" },
  { id: 168, value: "NO", label: "Noruega" },
  { id: 169, value: "OM", label: "Omán" },
  { id: 170, value: "PK", label: "Pakistán" },
  { id: 171, value: "PW", label: "Palau" },
  { id: 172, value: "PS", label: "Territorio Palestino, Ocupado" },
  { id: 173, value: "PA", label: "Panamá" },
  { id: 174, value: "PG", label: "Papúa Nueva Guinea" },
  { id: 175, value: "PY", label: "Paraguay" },
  { id: 176, value: "PE", label: "Perú" },
  { id: 177, value: "PH", label: "Filipinas" },
  { id: 178, value: "PN", label: "Pitcairn" },
  { id: 179, value: "PL", label: "Polonia" },
  { id: 180, value: "PT", label: "Portugal" },
  { id: 181, value: "PR", label: "Puerto Rico" },
  { id: 182, value: "QA", label: "Katar" },
  { id: 183, value: "RE", label: "Reunión" },
  { id: 184, value: "RO", label: "Rumania" },
  { id: 185, value: "RU", label: "Federación Rusa" },
  { id: 186, value: "RW", label: "Ruanda" },
  { id: 187, value: "BL", label: "San Bartolomé" },
  { id: 188, value: "SH", label: "Santa elena" },
  { id: 189, value: "KN", label: "Saint Kitts y Nevis" },
  { id: 190, value: "LC", label: "Santa Lucía" },
  { id: 191, value: "MF", label: "San Martín" },
  { id: 192, value: "PM", label: "San Pedro y Miquelón" },
  { id: 193, value: "VC", label: "San Vicente y las Granadinas" },
  { id: 194, value: "WS", label: "Samoa" },
  { id: 195, value: "SM", label: "San Marino" },
  { id: 196, value: "ST", label: "Santo Tomé y Príncipe" },
  { id: 197, value: "SA", label: "Arabia Saudita" },
  { id: 198, value: "SN", label: "Senegal" },
  { id: 199, value: "RS", label: "Serbia" },
  { id: 200, value: "CS", label: "Serbia y Montenegro" },
  { id: 201, value: "SC", label: "Seychelles" },
  { id: 202, value: "SL", label: "Sierra Leona" },
  { id: 203, value: "SG", label: "Singapur" },
  { id: 204, value: "SX", label: "San Martín" },
  { id: 205, value: "SK", label: "Eslovaquia" },
  { id: 206, value: "SI", label: "Eslovenia" },
  { id: 207, value: "SB", label: "Islas Salomón" },
  { id: 208, value: "SO", label: "Somalia" },
  { id: 209, value: "ZA", label: "Sudáfrica" },
  {
    id: 210,
    value: "GS",
    label: "Georgia del sur y las islas Sandwich del sur",
  },
  { id: 211, value: "SS", label: "Sudán del Sur" },
  { id: 212, value: "ES", label: "España" },
  { id: 213, value: "LK", label: "Sri Lanka" },
  { id: 214, value: "SD", label: "Sudán" },
  { id: 215, value: "SR", label: "Surinam" },
  { id: 216, value: "SJ", label: "Svalbard y Jan Mayen" },
  { id: 217, value: "SZ", label: "Swazilandia" },
  { id: 218, value: "SE", label: "Suecia" },
  { id: 219, value: "CH", label: "Suiza" },
  { id: 220, value: "SY", label: "República Árabe Siria" },
  { id: 221, value: "TW", label: "Taiwan, provincia de China" },
  { id: 222, value: "TJ", label: "Tayikistán" },
  { id: 223, value: "TZ", label: "Tanzania, República Unida de" },
  { id: 224, value: "TH", label: "Tailandia" },
  { id: 225, value: "TL", label: "Timor-Leste" },
  { id: 226, value: "TG", label: "Para llevar" },
  { id: 227, value: "TK", label: "Tokelau" },
  { id: 228, value: "TO", label: "Tonga" },
  { id: 229, value: "TT", label: "Trinidad y Tobago" },
  { id: 230, value: "TN", label: "Túnez" },
  { id: 231, value: "TR", label: "pavo" },
  { id: 232, value: "TM", label: "Turkmenistán" },
  { id: 233, value: "TC", label: "Islas Turcas y Caicos" },
  { id: 234, value: "TV", label: "Tuvalu" },
  { id: 235, value: "UG", label: "Uganda" },
  { id: 236, value: "UA", label: "Ucrania" },
  { id: 237, value: "AE", label: "Emiratos Árabes Unidos" },
  { id: 238, value: "GB", label: "Reino Unido" },
  { id: 239, value: "US", label: "Estados Unidos" },
  {
    id: 240,
    value: "UM",
    label: "Islas menores alejadas de los Estados Unidos",
  },
  { id: 241, value: "UY", label: "Uruguay" },
  { id: 242, value: "UZ", label: "Uzbekistan" },
  { id: 243, value: "VU", label: "Vanuatu" },
  { id: 244, value: "VE", label: "Venezuela" },
  { id: 245, value: "VN", label: "Vietnam" },
  { id: 246, value: "VG", label: "Islas Vírgenes Británicas" },
  { id: 247, value: "VI", label: "Islas Vírgenes, EE. UU." },
  { id: 248, value: "WF", label: "Wallis y Futuna" },
  { id: 249, value: "EH", label: "Sahara Occidental" },
  { id: 250, value: "YE", label: "Yemen" },
  { id: 251, value: "ZM", label: "Zambia" },
  { id: 252, value: "ZW", label: "Zimbabue" },
];

const countryOptionsPT = [
  { id: 1, value: "AF", label: "Afeganistão" },
  { id: 2, value: "AX", label: "Ilhas Aland" },
  { id: 3, value: "AL", label: "Albânia" },
  { id: 4, value: "DZ", label: "Argélia" },
  { id: 5, value: "AS", label: "Samoa Americana" },
  { id: 6, value: "AD", label: "Andorra" },
  { id: 7, value: "AO", label: "Angola" },
  { id: 8, value: "AI", label: "Anguilla" },
  { id: 9, value: "AQ", label: "Antártica" },
  { id: 10, value: "AG", label: "Antigua e Barbuda" },
  { id: 11, value: "AR", label: "Argentina" },
  { id: 12, value: "AM", label: "Armênia" },
  { id: 13, value: "AW", label: "Aruba" },
  { id: 14, value: "AU", label: "Austrália" },
  { id: 15, value: "AT", label: "Áustria" },
  { id: 16, value: "AZ", label: "Azerbaijão" },
  { id: 17, value: "BS", label: "Bahamas" },
  { id: 18, value: "BH", label: "Bahrain" },
  { id: 19, value: "BD", label: "Bangladesh" },
  { id: 20, value: "BB", label: "Barbados" },
  { id: 21, value: "BY", label: "Bielo-Rússia" },
  { id: 22, value: "BE", label: "Bélgica" },
  { id: 23, value: "BZ", label: "Belize" },
  { id: 24, value: "BJ", label: "Benin" },
  { id: 25, value: "BM", label: "Bermudas" },
  { id: 26, value: "BT", label: "Butão" },
  { id: 27, value: "BO", label: "Bolívia" },
  { id: 28, value: "BQ", label: "Bonaire, Sint Eustatius e Saba" },
  { id: 29, value: "BA", label: "Bósnia e Herzegovina" },
  { id: 30, value: "BW", label: "Botswana" },
  { id: 31, value: "BV", label: "Ilha Bouvet" },
  { id: 32, value: "BR", label: "Brasil" },
  { id: 33, value: "IO", label: "Território Britânico do Oceano Índico" },
  { id: 34, value: "BN", label: "Brunei Darussalam" },
  { id: 35, value: "BG", label: "Bulgária" },
  { id: 36, value: "BF", label: "Burkina Faso" },
  { id: 37, value: "BI", label: "Burundi" },
  { id: 38, value: "KH", label: "Camboja" },
  { id: 39, value: "CM", label: "Camarões" },
  { id: 40, value: "CA", label: "Canadá" },
  { id: 41, value: "CV", label: "cabo Verde" },
  { id: 42, value: "KY", label: "Ilhas Cayman" },
  { id: 43, value: "CF", label: "República Centro-Africana" },
  { id: 44, value: "TD", label: "Chade" },
  { id: 45, value: "CL", label: "Chile" },
  { id: 46, value: "CN", label: "China" },
  { id: 47, value: "CX", label: "Ilha do Natal" },
  { id: 48, value: "CC", label: "Ilhas Cocos (Keeling)" },
  { id: 49, value: "CO", label: "Colômbia" },
  { id: 50, value: "KM", label: "Comores" },
  { id: 51, value: "CG", label: "Congo" },
  { id: 52, value: "CD", label: "Congo, República Democrática do Congo" },
  { id: 53, value: "CK", label: "Ilhas Cook" },
  { id: 54, value: "CR", label: "Costa Rica" },
  { id: 55, value: "CI", label: "Cote D'Ivoire" },
  { id: 56, value: "HR", label: "Croácia" },
  { id: 57, value: "CU", label: "Cuba" },
  { id: 58, value: "CW", label: "Curaçao" },
  { id: 59, value: "CY", label: "Chipre" },
  { id: 60, value: "CZ", label: "República Checa" },
  { id: 61, value: "DK", label: "Dinamarca" },
  { id: 62, value: "DJ", label: "Djibouti" },
  { id: 63, value: "DM", label: "Dominica" },
  { id: 64, value: "DO", label: "República Dominicana" },
  { id: 65, value: "EC", label: "Equador" },
  { id: 66, value: "EG", label: "Egito" },
  { id: 67, value: "SV", label: "El Salvador" },
  { id: 68, value: "GQ", label: "Guiné Equatorial" },
  { id: 69, value: "ER", label: "Eritreia" },
  { id: 70, value: "EE", label: "Estônia" },
  { id: 71, value: "ET", label: "Etiópia" },
  { id: 72, value: "FK", label: "Ilhas Falkland (Malvinas)" },
  { id: 73, value: "FO", label: "ilhas Faroe" },
  { id: 74, value: "FJ", label: "Fiji" },
  { id: 75, value: "FI", label: "Finlândia" },
  { id: 76, value: "FR", label: "França" },
  { id: 77, value: "GF", label: "Guiana Francesa" },
  { id: 78, value: "PF", label: "Polinésia Francesa" },
  { id: 79, value: "TF", label: "Territórios Franceses do Sul" },
  { id: 80, value: "GA", label: "Gabão" },
  { id: 81, value: "GM", label: "Gâmbia" },
  { id: 82, value: "GE", label: "Georgia" },
  { id: 83, value: "DE", label: "Alemanha" },
  { id: 84, value: "GH", label: "Gana" },
  { id: 85, value: "GI", label: "Gibraltar" },
  { id: 86, value: "GR", label: "Grécia" },
  { id: 87, value: "GL", label: "Groenlândia" },
  { id: 88, value: "GD", label: "Grenada" },
  { id: 89, value: "GP", label: "Guadalupe" },
  { id: 90, value: "GU", label: "Guam" },
  { id: 91, value: "GT", label: "Guatemala" },
  { id: 92, value: "GG", label: "Guernsey" },
  { id: 93, value: "GN", label: "Guiné" },
  { id: 94, value: "GW", label: "Guinea-bissau" },
  { id: 95, value: "GY", label: "Guiana" },
  { id: 96, value: "HT", label: "Haiti" },
  { id: 97, value: "HM", label: "Ilha Heard e Ilhas McDonald" },
  { id: 98, value: "VA", label: "Santa Sé (Estado da Cidade do Vaticano)" },
  { id: 99, value: "HN", label: "Honduras" },
  { id: 100, value: "HK", label: "Hong Kong" },
  { id: 101, value: "HU", label: "Hungria" },
  { id: 102, value: "IS", label: "Islândia" },
  { id: 103, value: "IN", label: "Índia" },
  { id: 104, value: "ID", label: "Indonésia" },
  { id: 105, value: "IR", label: "Irã (Republic Islâmica do Irã" },
  { id: 106, value: "IQ", label: "Iraque" },
  { id: 107, value: "IE", label: "Irlanda" },
  { id: 108, value: "IM", label: "Ilha de Man" },
  { id: 109, value: "IL", label: "Israel" },
  { id: 110, value: "IT", label: "Itália" },
  { id: 111, value: "JM", label: "Jamaica" },
  { id: 112, value: "JP", label: "Japão" },
  { id: 113, value: "JE", label: "Jersey" },
  { id: 114, value: "JO", label: "Jordânia" },
  { id: 115, value: "KZ", label: "Cazaquistão" },
  { id: 116, value: "KE", label: "Quênia" },
  { id: 117, value: "KI", label: "Kiribati" },
  { id: 118, value: "KP", label: "Coréia, República Popular Democrática da" },
  { id: 119, value: "KR", label: "Republica da Coréia" },
  { id: 120, value: "XK", label: "Kosovo" },
  { id: 121, value: "KW", label: "Kuwait" },
  { id: 122, value: "KG", label: "Quirguistão" },
  { id: 123, value: "LA", label: "República Democrática Popular do Laos" },
  { id: 124, value: "LV", label: "Letônia" },
  { id: 125, value: "LB", label: "Líbano" },
  { id: 126, value: "LS", label: "Lesoto" },
  { id: 127, value: "LR", label: "Libéria" },
  { id: 128, value: "LY", label: "Jamahiriya Árabe da Líbia" },
  { id: 129, value: "LI", label: "Liechtenstein" },
  { id: 130, value: "LT", label: "Lituânia" },
  { id: 131, value: "LU", label: "Luxemburgo" },
  { id: 132, value: "MO", label: "Macau" },
  { id: 133, value: "MK", label: "Macedônia, Antiga República Iugoslava da" },
  { id: 134, value: "MG", label: "Madagáscar" },
  { id: 135, value: "MW", label: "Malawi" },
  { id: 136, value: "MY", label: "Malásia" },
  { id: 137, value: "MV", label: "Maldivas" },
  { id: 138, value: "ML", label: "Mali" },
  { id: 139, value: "MT", label: "Malta" },
  { id: 140, value: "MH", label: "Ilhas Marshall" },
  { id: 141, value: "MQ", label: "Martinica" },
  { id: 142, value: "MR", label: "Mauritânia" },
  { id: 143, value: "MU", label: "Maurício" },
  { id: 144, value: "YT", label: "Mayotte" },
  { id: 145, value: "MX", label: "México" },
  { id: 146, value: "FM", label: "Micronésia, Estados Federados da" },
  { id: 147, value: "MD", label: "Moldávia, República da" },
  { id: 148, value: "MC", label: "Mônaco" },
  { id: 149, value: "MN", label: "Mongólia" },
  { id: 150, value: "ME", label: "Montenegro" },
  { id: 151, value: "MS", label: "Montserrat" },
  { id: 152, value: "MA", label: "Marrocos" },
  { id: 153, value: "MZ", label: "Moçambique" },
  { id: 154, value: "MM", label: "Myanmar" },
  { id: 155, value: "NA", label: "Namibia" },
  { id: 156, value: "NR", label: "Nauru" },
  { id: 157, value: "NP", label: "Nepal" },
  { id: 158, value: "NL", label: "Países Baixos" },
  { id: 159, value: "AN", label: "Antilhas Holandesas" },
  { id: 160, value: "NC", label: "Nova Caledônia" },
  { id: 161, value: "NZ", label: "Nova Zelândia" },
  { id: 162, value: "NI", label: "Nicarágua" },
  { id: 163, value: "NE", label: "Níger" },
  { id: 164, value: "NG", label: "Nigéria" },
  { id: 165, value: "NU", label: "Niue" },
  { id: 166, value: "NF", label: "Ilha Norfolk" },
  { id: 167, value: "MP", label: "Ilhas Marianas do Norte" },
  { id: 168, value: "NO", label: "Noruega" },
  { id: 169, value: "OM", label: "Omã" },
  { id: 170, value: "PK", label: "Paquistão" },
  { id: 171, value: "PW", label: "Palau" },
  { id: 172, value: "PS", label: "Território Palestino, Ocupado" },
  { id: 173, value: "PA", label: "Panamá" },
  { id: 174, value: "PG", label: "Papua Nova Guiné" },
  { id: 175, value: "PY", label: "Paraguai" },
  { id: 176, value: "PE", label: "Peru" },
  { id: 177, value: "PH", label: "Filipinas" },
  { id: 178, value: "PN", label: "Pitcairn" },
  { id: 179, value: "PL", label: "Polônia" },
  { id: 180, value: "PT", label: "Portugal" },
  { id: 181, value: "PR", label: "Porto Rico" },
  { id: 182, value: "QA", label: "Catar" },
  { id: 183, value: "RE", label: "Reunião" },
  { id: 184, value: "RO", label: "Romênia" },
  { id: 185, value: "RU", label: "Federação Russa" },
  { id: 186, value: "RW", label: "Ruanda" },
  { id: 187, value: "BL", label: "São Bartolomeu" },
  { id: 188, value: "SH", label: "Santa Helena" },
  { id: 189, value: "KN", label: "São Cristóvão e Neves" },
  { id: 190, value: "LC", label: "Santa Lúcia" },
  { id: 191, value: "MF", label: "são Martinho" },
  { id: 192, value: "PM", label: "São Pedro e Miquelão" },
  { id: 193, value: "VC", label: "São Vicente e Granadinas" },
  { id: 194, value: "WS", label: "Samoa" },
  { id: 195, value: "SM", label: "San Marino" },
  { id: 196, value: "ST", label: "São Tomé e Príncipe" },
  { id: 197, value: "SA", label: "Arábia Saudita" },
  { id: 198, value: "SN", label: "Senegal" },
  { id: 199, value: "RS", label: "Sérvia" },
  { id: 200, value: "CS", label: "Sérvia e Montenegro" },
  { id: 201, value: "SC", label: "Seychelles" },
  { id: 202, value: "SL", label: "Serra Leoa" },
  { id: 203, value: "SG", label: "Cingapura" },
  { id: 204, value: "SX", label: "St Martin" },
  { id: 205, value: "SK", label: "Eslováquia" },
  { id: 206, value: "SI", label: "Eslovênia" },
  { id: 207, value: "SB", label: "Ilhas Salomão" },
  { id: 208, value: "SO", label: "Somália" },
  { id: 209, value: "ZA", label: "África do Sul" },
  { id: 210, value: "GS", label: "Geórgia do Sul e Ilhas Sandwich do Sul" },
  { id: 211, value: "SS", label: "Sudão do Sul" },
  { id: 212, value: "ES", label: "Espanha" },
  { id: 213, value: "LK", label: "Sri Lanka" },
  { id: 214, value: "SD", label: "Sudão" },
  { id: 215, value: "SR", label: "Suriname" },
  { id: 216, value: "SJ", label: "Svalbard e Jan Mayen" },
  { id: 217, value: "SZ", label: "Suazilândia" },
  { id: 218, value: "SE", label: "Suécia" },
  { id: 219, value: "CH", label: "Suíça" },
  { id: 220, value: "SY", label: "República Árabe da Síria" },
  { id: 221, value: "TW", label: "Taiwan, província da China" },
  { id: 222, value: "TJ", label: "Tajiquistão" },
  { id: 223, value: "TZ", label: "Tanzânia, República Unida da" },
  { id: 224, value: "TH", label: "Tailândia" },
  { id: 225, value: "TL", label: "Timor-Leste" },
  { id: 226, value: "TG", label: "Ir" },
  { id: 227, value: "TK", label: "Tokelau" },
  { id: 228, value: "TO", label: "Tonga" },
  { id: 229, value: "TT", label: "Trinidad e Tobago" },
  { id: 230, value: "TN", label: "Tunísia" },
  { id: 231, value: "TR", label: "Peru" },
  { id: 232, value: "TM", label: "Turcomenistão" },
  { id: 233, value: "TC", label: "Ilhas Turcas e Caicos" },
  { id: 234, value: "TV", label: "Tuvalu" },
  { id: 235, value: "UG", label: "Uganda" },
  { id: 236, value: "UA", label: "Ucrânia" },
  { id: 237, value: "AE", label: "Emirados Árabes Unidos" },
  { id: 238, value: "GB", label: "Reino Unido" },
  { id: 239, value: "US", label: "Estados Unidos" },
  { id: 240, value: "UM", label: "Ilhas Menores Distantes dos Estados Unidos" },
  { id: 241, value: "UY", label: "Uruguai" },
  { id: 242, value: "UZ", label: "Uzbequistão" },
  { id: 243, value: "VU", label: "Vanuatu" },
  { id: 244, value: "VE", label: "Venezuela" },
  { id: 245, value: "VN", label: "Viet Nam" },
  { id: 246, value: "VG", label: "Ilhas Virgens Britânicas" },
  { id: 247, value: "VI", label: "Ilhas Virgens, EUA" },
  { id: 248, value: "WF", label: "Wallis e Futuna" },
  { id: 249, value: "EH", label: "Saara Ocidental" },
  { id: 250, value: "YE", label: "Iémen" },
  { id: 251, value: "ZM", label: "Zâmbia" },
  { id: 252, value: "ZW", label: "Zimbábue" },
];

const countryOptions = {
  en: countryOptionsEN,
  fr: countryOptionsFR,
  es: countryOptionsES,
  pt: countryOptionsPT,
};

export default countryOptions;
